"""Initial migration UserLogin

Revision ID: 8f60a5a0b3ab
Revises: 2ffdf7310f4d
Create Date: 2024-07-17 11:11:02.268162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f60a5a0b3ab'
down_revision: Union[str, None] = '2ffdf7310f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_login', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users_login', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_login', type_='foreignkey')
    op.drop_column('users_login', 'user_id')
    # ### end Alembic commands ###
